GoMudEngine/GoMud

_datafiles/quests/2.yaml, characters/character.go, mobs/mobs.go, rooms/rooms.go, world.go
* Mobs that hold a quest the player is working on have a (!) flag after their name now.
* Moved `look` auto complete logic to own section to allow it to contain exit and container names
=> Added visual quest flag on mobs with active player quest

_datafiles/config.yaml, configs/configs.go, connection/connection.go, inputhandlers/login.go, inputhandlers/systemcommands.go, main.go, users/userrecord.go, users/users.go, world.go
To avoid players being able to disconnect as an exploit to avoid dying etc., we want a zombie period where their character remains in play even though their network connection is gone.
Later this may be enhanced to allow auto-behavior for the player.
* Added new config values related to zombification period
* Players can reconnect to their zombie self 
* `/quit` command now just disconnects the network and basically zombifies them.
=> Adding a zombie period when disconnecting

_datafiles/keywords.yaml, characters/character.go, usercommands/buy.go, usercommands/macros.go, usercommands/set.go, webclient/webclient.html, world.go
This addresses some bugs and quirks found during live testing.
* `broadcast`/`train`/`tame` commands added to help list
* Default character description no longer includes a name, avoiding using the account name instead of (possibly unset) character name.
* Fixed a bug with macros causing a crash
* `macro` aliased to `macros` for both command and helpfiles.
* Improved macro display, brake down into individual commands and display (see example below)
* Added some restrictions to macros:
* limit to 15 commands
* commands cannot be empty
* Added function key (`F1` to `=1`, `F2` to `=2` etc.) support to web client.
Macro display (`macro` command):
=> Misc fixes

_datafiles/config.yaml, _datafiles/mobs/frostfang/scripts/38-player_guide.js, _datafiles/rooms/tutorial/903.js, _datafiles/rooms/tutorial/993.js, _datafiles/templates/help/skulduggery.template, configs/configs.go, mobcommands/go.go, mobcommands/look.go, mobcommands/portal.go, mobcommands/shoot.go, mobcommands/throw.go, mobcommands/wander.go, rooms/roommanager.go, scripting/docs/FUNCTIONS_ACTORS.md, usercommands/admin.room.go, usercommands/go.go, usercommands/lock.go, usercommands/look.go, usercommands/picklock.go, usercommands/shoot.go, usercommands/skill.brawling.throw.go, usercommands/skill.portal.go, usercommands/skill.skulduggery.bump.go, usercommands/unlock.go, world.roundtick.go
This is to facilitate custom start rooms other than town square, especially as players build out their own worlds.
It also contains a fix for the `bump` command that was causing crashes.
* `StartRoom` added to `config.yaml`
* Updated references to sending players to room 1 (town square) to use `0` (zero) as an alias to "StartRoom"
* Lots of code changes that disregarded room 0, now allow it.
* Fixed `bump` when no target specified would crash.
* Updated `bump` helpfile to indicate how to use it.
=> Adding "StartRoom" config override. Fixing bump command.

_datafiles/keywords.yaml, _datafiles/templates/help/put.template, rooms/container.go, usercommands/look.go, usercommands/put.go, usercommands/storage.go, usercommands/usercommands.go
While players can take things out of containers, they cannot put things into containers. This fixes that.
* Added `put` command (alias `place`)
* If a player uses the `store`/`storage` command outside of a storage are and a container is present, recommends using `put`
* Now saving chest contents since there could be unexpected items placed into them.
* Minor fix to some messaging.
=> Put gold and items into containers

_datafiles/templates/admincommands/help/command.grant.template, internal/mobcommands/suicide.go, internal/scripting/actor_func.go, internal/scripting/docs/FUNCTIONS_ACTORS.md, internal/usercommands/admin.grant.go, internal/usercommands/trash.go, internal/usercommands/usercommands.go, internal/users/userrecord.go, world.go
* Experience granting done through user.GrantXP() will now use a centralized message and include the reason for the xp (combat, trash cleanup, etc)
* Added a script command to grantXP to actors
* Added an admin command to `grant <username> <amount> experience`
=> Experience grant centralizing

_datafiles/keywords.yaml, _datafiles/templates/help/history.template, internal/inputhandlers/systemcommands.go, internal/usercommands/character.go, internal/usercommands/history.go, internal/usercommands/start.go, internal/usercommands/suicide.go, internal/usercommands/usercommands.go, internal/users/userlog.go, internal/users/userrecord.go, internal/users/users.go, main.go, world.go, world.roundtick.go
* Users can now view a log of recent activity through the `history` (alias: `log`) command.
* Can narrow down logs by category such as `history experience`
=> Adding ephemeral `history` for users

_datafiles/ansi-aliases.yaml, _datafiles/config.yaml, _datafiles/keywords.yaml, _datafiles/mutators/pushed_boulder.yaml, _datafiles/rooms/stormshards/1001.yaml, _datafiles/rooms/stormshards/593.js, _datafiles/rooms/stormshards/593.yaml, _datafiles/templates/admincommands/help/command.paz.template, _datafiles/templates/admincommands/help/command.zap.template, _datafiles/templates/descriptions/who.template, internal/characters/character.go, internal/characters/kdstats.go, internal/combat/combat.go, internal/mobcommands/suicide.go, internal/mobs/mobs.go, internal/moons/moons.go, internal/mutators/mutators.go, internal/scripting/docs/FUNCTIONS_ROOMS.md, internal/scripting/room.go, internal/scripting/room_func.go, internal/usercommands/admin.paz.go, internal/usercommands/admin.room.go, internal/usercommands/admin.zap.go, internal/usercommands/killstats.go, internal/usercommands/start.go, internal/usercommands/suicide.go, internal/usercommands/usercommands.go, world.go, world.roundtick.go
* Added stormshards content (push boulder), to be expanded upon later (tests ephemeral mutator exit via scripting)
* Updated room scripting: `room.HasMutator()`
* Added `paz` command (inverse of `zap`) to quick recover hp/mp.
* Added better color style to `zap`/`paz`
* Fixed spellcasting bug where it would assuming player was trying to `go` when in combat and reject.
* Improved magic combat tracking for experience gains and mob death.
* Added keywords for targeting self in commands: `self`, `myself`, `me`
* Currently only applies to commands where the END of the command is the target name. May not apply to all cases (unsure)
* Example: `look at self`, `look at me`, `give potion to myself` etc., useful when targeting for spells or admin commands.
* Added default color for room script …
=> Magic fixes, admin commands, self keywords

_datafiles/config.yaml, _datafiles/mutators/pvp_enabled.yaml, _datafiles/rooms/frostfang_slums/439.yaml, _datafiles/spells/sparks.js, _datafiles/spells/sparks.yaml, _datafiles/templates/descriptions/room-title.template, internal/configs/configs.go, internal/mutators/mutators.go, internal/rooms/roomdetails.go, internal/rooms/rooms.go, internal/usercommands/ask.go, internal/usercommands/attack.go, internal/usercommands/print.go, internal/usercommands/skill.brawling.throw.go, internal/usercommands/skill.cast.go, internal/usercommands/skill.skulduggery.backstab.go, internal/usercommands/skill.skulduggery.bump.go, internal/usercommands/skill.skulduggery.pickpocket.go, internal/usercommands/spells.go, internal/usercommands/usercommands.go, world.go
* Adjusting pvp config value to a string:
* `enabled` - PVP is allowed everywhere.
* `disabled` - PVP is never allowed.
* `limited` (default) - PVP is allowed in designated areas
* Rooms have a property `pvp` which can be set true to allow a specific room to be pvp-enabled.
* Mutators have a `pvp` property which can be set: `pvp.enabled` or `pvp.disabled` to override/force pvp to a specific on/off state in a room.
* Added a `pvp-enabled` mutator that demonstrates enabling pvp via mutator, and applied it to the entire frostfang slums area.
* Added a `sparks` spell to test harmful spells that target groups
Example PVP warning:
=> PVP Config, measuring tool, sparks spell

_datafiles/templates/tables/shoplist.template, internal/characters/shop.go, internal/usercommands/buy.go, internal/usercommands/list.go, internal/usercommands/sell.go
* Shops can now require items in addition to gold for trade in purchasing.
* Can require zero gold and only an item.
* When gold is zero (default if unspecified), item prices are calculated dynamically. Therefore, a `-1` value must be specified in order to require ZERO gold.
* Shop lists with color "cells" were not padding/rendering correctly. This fixes that template.
=> Support for shop item trade-ins. Fixing padding in shop table

internal/configs/config_types.go, internal/configs/configs.go, main.go, world.go
* RoundCount is saved to `config-overrides.yaml` every 10 seconds
* When GoMud starts up, if a value is found, it uses it, otherwise falls back to default startup conditions.
=> Saving current round count every 10 seconds

internal/connections/connectiondetails.go, internal/connections/connections.go, internal/connections/heartbeat.go
Implemented WebSocket ping/pong heartbeat mechanism to maintain connection health. Each connection gets its own heartbeat manager to handle periodic pings and monitor pong responses.
Potential considerations:
- Check if a heartbeat manager is already running before starting another
- Ensure proper cleanup on error cases
- Distinguish between normal closures and errors
This is a first implementation that covers the basic needs. We can revisit these considerations if they become actual issues.
=> [Feat] Add WebSocket heartbeat implementation

.github/workflows/build.yml, .gitignore, README.md
This PR adds a CI/CD workflow to GoMud.
GoMud now automatically builds and release to branch changes to `master`.
This should make running the mud more approachable for less technically savvy users.
(It also appears my auto-linter went to town on the markdown file)
=> feat: Add ci/cd workflow to GoMud

internal/util/util.go, internal/util/util_test.go, main.go
* Added unit tests for util.go (96.2% code coverage)
* Some code adjustments/fixes to support better unit testing of functions
* Some code fixes to bad logic that was found
=> Unit Tests for util.go

_datafiles/world/default/audio.yaml, _datafiles/world/empty/audio.yaml, internal/audio/audio.go, internal/combat/combat.go, internal/mobcommands/go.go, internal/rooms/rooms.go, internal/usercommands/buy.go, internal/usercommands/go.go, internal/usercommands/use.go, internal/users/userrecord.go, main.go, world.go, world.roundtick.go
* Added a new config file: `audio.yaml`
* Audio can be played by an ID or by filepath.
* When ID is used, other config values taken into consideration such as optional volume setting.
=> audio config map

_datafiles/world/default/templates/admincommands/help/command.room.template, _datafiles/world/empty/templates/admincommands/help/command.room.template, internal/items/itemspec.go, internal/rooms/rooms.go, internal/usercommands/admin.room.go
* Interactive menu to edit exits added
* Invoke via `room edit exits`
=> Room edit "exits" command

_datafiles/world/default/templates/admincommands/help/command.room.template, _datafiles/world/empty/templates/admincommands/help/command.room.template, internal/usercommands/admin.room.go
* `room edit mutators` command added
* Provides a basic way to toggle on/off multiple mutators for the room
* Note: NOT THE ZONE.
* Added a toggle for `room edit exit` to set exits to secret/hidden.
=> Room edit mutators command.

_datafiles/world/default/templates/admincommands/help/command.zone.template, _datafiles/world/empty/templates/admincommands/help/command.zone.template, internal/usercommands/admin.zone.go
* `zone edit` command to edit properties of the zone
=> "Zone edit" command

internal/usercommands/go.go, internal/usercommands/usercommands.go, world.go
* Added a user command flag which can be used to block input from the user until a multi-turn command finishes.
=> BlockInput flag

_datafiles/config.yaml, _datafiles/html/public/_header.html, _datafiles/html/public/webclient.html, internal/configs/configs.go, internal/web/home.go, internal/web/template_func.go, internal/web/web.go
* Added `MudName` config - should be name of mud.
* Injecting `MudName` various web places (webclient connect button, page titles, page header nav)
* Using defined webport in config for webclient (was hard coded)
Example:
=> Misc. Web Customizations

_datafiles/html/public/online.html, _datafiles/html/public/viewconfig.html, _datafiles/html/static/public/css/gomud.css
* Centralized CSS color definitions to top of css file in var()'s to make an easily adjusted palette.
* Moved table css out of individual files and into global css.
=> CSS Color Palette

.gitignore, internal/integrations/discord/client.go, internal/integrations/discord/listeners.go, internal/integrations/discord/types.go, main.go
This PR adds a very simple discord integration to GoMud.
To use the integration:
1. Setup a discord webhook: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
2. Set the environment variable "DISCORD_WEBHOOK_URL" prior to running GoMud. (`DISCORD_WEBHOOK_URL=https://www.mywebhook.com ./gomud` on linux).
All feedback is encouraged and welcome, learning Golang slowly.
=> feature: adds discord integration to GoMud

internal/configs/configs.go
When the config overrides file is loaded, if a key is provided that is unrecognized, it sends an error and aborts loading the overrides file.
This is a problem, since it then fails over to default values (Web Port etc).
* Changed overrides loading to log an error instead of returning an error, and just skips the single bad keyname.
=> Config Override Bad Data Fix

internal/buffs/buffs.go
Invalid value for field `buffId` in the user file `_datafiles/world/empty/users/1.yaml`
error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9ee7cd]
goroutine 40 [running]:
github.com/volte6/gomud/internal/buffs.(*Buffs).Validate(0xc000258228, {0x0, 0x0, 0x0})
/home/lostsnow/projects/github/mud/GoMud/internal/buffs/buffs.go:62 +0x2ed
github.com/volte6/gomud/internal/characters.(*Character).Validate(0xc000258008, {0xc00015a20e, 0x1, 0x1})
/home/lostsnow/projects/github/mud/GoMud/internal/characters/character.go:1479 +0x365
github.com/volte6/gomud/internal/users.LoadUser({0xc000504260, 0x5}, {0x0, 0x0, 0x0})
/home/lostsnow/projects/github/mud/GoMud/internal/users/users.go:380 +0x6ce …
```
=> Fix invalid charactor buffId cause nil pointer panic

_datafiles/world/default/mobs/frostfang/scripts/2-guard-hungry.js, _datafiles/world/default/rooms/frostfang/776.yaml, _datafiles/world/default/rooms/frostfang/777.yaml, _datafiles/world/default/rooms/frostfang/778.yaml, _datafiles/world/default/rooms/frostfang/779.yaml, _datafiles/world/default/rooms/frostfang/780.yaml, _datafiles/world/default/rooms/frostfang/781.yaml, _datafiles/world/default/rooms/frostfang/782.yaml, _datafiles/world/default/rooms/nowhere/-1.yaml, _datafiles/world/empty/rooms/shadow_realm/-1.yaml, internal/characters/character.go, internal/inputhandlers/login.go, internal/items/items.go, internal/rooms/roommanager.go, internal/usercommands/character.go, internal/usercommands/look.go, internal/usercommands/set.go, internal/usercommands/start.go, internal/users/userrecord.go, internal/users/users.go
* Default tinymap on, except in the void
* Fixed some quirky behavior of the hungry guard quest script
* Added a "use" suggestion when looking at usable items
* Miscellaneous cleanup of room descriptions.
* Added a warning about username/login name vs. character name when creating a new account.
* Fixed a bug where new users could sign up with the same name before the user was saved.
* Character name no longer set to login name when creating a new account, revealing the login identity. Now uses a temp name until a character name is chosen.
* Added option to skip tutorial if the user account is over an hour old.
=> Testing bugs

_datafiles/world/default/rooms/catacombs/136.yaml, _datafiles/world/default/rooms/dark_forest/565.yaml, _datafiles/world/default/rooms/dark_forest/568.yaml, _datafiles/world/default/rooms/frost_lake/319.yaml, _datafiles/world/default/rooms/frostfang/1.yaml, _datafiles/world/default/rooms/frostfang/18.yaml, _datafiles/world/default/rooms/frostfang/26.yaml, _datafiles/world/empty/plugin-data/READMD.md, _datafiles/world/empty/plugin-data/README.md, internal/hooks/NewRound_UserRoundTick.go, internal/hooks/NewTurn_AutoSave.go, internal/rooms/zoneconfig.go, main.go, modules/leaderboard.go
* Fixed a filename typo (`READMD.md` => `README.md`)
* Adding `plugins.Save()` to autosave event listener.
* Fixed repeating Noun definitions, made into aliases
* Removed debugging `fmt.Println()`
* Added idlemessages in Zone config.
* If idlemessages are defined for a room, they always take priority.
=> Miscellaneous Adjustments

internal/hooks/RoomChange_LocationGMCPUpdates.go, internal/mapper/mapper.go
* `coords` added for rooms with known coordinates.
* Non compass direction exit names excluded from exits list
* `exitsv2` data node added with more details about exits
* target room `num`
* `dx`, `dy`, `dz` delta directions of target room
* `locked` true/false
* `haskey` true/false
* `haspickcombo` true/false
=> GMCP Room Info updates

internal/templates/templatesfunctions.go, internal/templates/templatesfunctions_test.go, internal/util/util.go, internal/util/util_test.go
Miscellaneous adjustments to accomodate string manipulation in languages other than english.
See: internal/templates/templatesfunctions_test.go
=> Fix some template pad functions with wide charactors

modules/gmcp.go
* Fixing a bug for GMCP data sent as string payload, double appending module name.
=> GMCP Bug fix

_datafiles/world/default/templates/admincommands/help/command.reload.template, _datafiles/world/empty/templates/admincommands/help/command.reload.template, internal/language/language.go, internal/language/language_test.go, internal/language/testdata/reload-test/.gitignore, internal/usercommands/admin.reload.go
Admin can reload runtime translation localize files using the command `reload translations`
=> Add cmd reload translations

internal/plugins/plugins.go, internal/util/util.go
Some warnings are too verbose or uninformative when first running the codebase. This addresses some of it.
- Do not log warnings when plugins can't find a data file.
- Add (first time running?) message with missing round data warning.
- Fix a condition that leads to unnecessary logging.
- Removed an unnecessary line of code.
=> Fixing warnings when running for first time

_datafiles/world/default/mobs/frostfang/scripts/26-frostfang_citizen-locketsadness.js
The Sophie script in frostfang has some code that errors out when run. This was mistakenly copied from another script.
This change removes that code.
- Removed offending "lich subject" related code.
=> Script error fix (sophie's locked - frostfang)

internal/hooks/Message_SendMessages.go
Fixes a bug introduced last month, causing room messages to not go out properly.
- Do not skip entire event when skipping one user.
=> Fixing bug with room messages not sending

internal/connections/connections.go, internal/events/eventtypes.go, internal/hooks/NewRound_InactivePlayers.go, internal/hooks/NewTurn_CleanupZombies.go, internal/inputhandlers/login.go, internal/inputhandlers/systemcommands.go, internal/users/users.go, world.go
When a user is already logged in, and tries to log in again, it denies them and disconnects.
However, there may be situations where they are not really logged in, and something is maintaining the connection, preventing them from logging in until an inactivity timeout kicks the "almost zombie" user.
This adds a prompt to the login process allowing a second login to optionally kick the first login, and replace them.
- Added a new prompt: "User is already connected. Kick them?"
- When `no` is selected, they are denied login as it is currently.
- When `yes` is selected, the currently connected user is kicked, and the new login replaces them.
- Removed some unused code/functions
=> Adding a prompt for kicking user when double-logging in

_datafiles/world/default/mobs/frostfang/scripts/2-guard.js, _datafiles/world/default/mobs/frostfang/scripts/26-frostfang_citizen-locketsadness.js, internal/hooks/Message_SendMessages.go, internal/hooks/NewRound_IdleMobs.go, internal/mapper/mapper.path.go, internal/mapper/mapper.path_test.go, internal/mobcommands/go.go, internal/mobcommands/mobcommands.go, internal/mobcommands/pathto.go, internal/mobcommands/wander.go, internal/mobs/mobs.go, internal/mobs/mobs_path.go, internal/scripting/actor_func.go, internal/usercommands/admin.locate.go, main.go
This adds initial implementation of pathfinding for mobs. 
A `pathto` command is added, which accepts multiple room id's, or the keyword `home` (to go back to their spawned-from room) to initiate a path for a mob. This allows testing via the admin `command` command, and also initiating via scripting.
- Paths are followed when mobs are idle
- `pathto` command added.
- Example: `pathto 300 1 home` to create/follow a path to roomId 300, then 1, then back to home room.
- If rooms cannot be fully connected, `pathto` fails without a path.
- Removed old "room stack" tracking used to return home when mobs wander too far. It was buggy anyways. Replaced with `pathto home`
- Added some randomly selected paths for frostfang …
=> Mob pathfinding

internal/connections/clientsettings.go, internal/templates/layout.go, internal/templates/layout_test.go, internal/usercommands/admin.item.go, internal/usercommands/admin.mob.go
This Pull Request introduces a new dynamic list rendering system and applies it to the mob and item listing commands. It also adds safe accessor methods for screen dimensions and improves handling when no items are found.
**NOTE:** This PR could be followed up with changes to improve `DynamicList`.
- Added getters for screen width and height that provide sensible default values when the client hasn’t reported its dimensions, and cast from uint32 to int for downstream compatibility.
- Added templates/layout.go containing the shared `DynamicList` function, as part of a larger refactor to centralize list rendering logic.
- Changed both the mob list and item list commands to use `DynamicList` for output generation, and ensured case-insensitive sorting by lowercasing names before comparison.
- …
=> Update mob and item list functionality

internal/usercommands/character.go
The `character` command only works at level 5 and above. Creating an alt makes them level 1, not allowing them to switch back to their original character.
This fixes it.
- Command works at level 5 OR if they have alt characters in storage.
https://github.com/GoMudEngine/GoMud/issues/349
=> Allow `character` command at low level if they have alts

_datafiles/guides/building/scripting/FUNCTIONS_ACTORS.md, _datafiles/guides/building/scripting/SCRIPTING_MOBS.md, _datafiles/world/default/conversations/frostfang/40.yaml, _datafiles/world/default/mobs/frostfang/40-rodric.yaml, _datafiles/world/default/mobs/frostfang/scripts/26-frostfang_citizen-lakeworker.js, _datafiles/world/default/mobs/frostfang/scripts/40-rodric.js, internal/conversations/conversations.go, internal/hooks/MobIdle_HandleIdleMobs.go, internal/hooks/NewRound_IdleMobs.go, internal/mapper/mapper.path.go, internal/mobcommands/converse.go, internal/mobcommands/go.go, internal/mobcommands/pathto.go, internal/mobcommands/portal.go, internal/mobcommands/shout.go, internal/mobs/mobs.go, world.go
Adds additional scriptability around pathing, and fixes some small bugs and quirks.
- Add scripting documentation for actors and mobs
- Rewrote parts of lakeworker script to use pathfinding.
- Improved lakeworker script to do a little more while pathing.
- Added script event functions for various stages of a path.
- Fixed misbehavior of mob `shout` command.
- Updated command processing so that mobs subject to similar waiting rules as players when commands are queued with delays.
- Added caching for mobs that cannot find a path home.
- Mobs that can't go home receive an adjective `lost`
- Fixed some conversation bugginess, added some caching
- Moved `Rodric` to frostfang folder, where he should be.
- Improved Rodric scripting slightly to have some more interesting behavior.
=> Mob pathing additions

internal/mapper/mapper.go, internal/mapper/mapper.path.go, internal/rooms/roommanager.go, internal/scripting/room_func.go, internal/usercommands/admin.build.go, internal/usercommands/admin.teleport.go, internal/usercommands/look.go, internal/usercommands/skill.map.go, modules/gmcp/gmcp.Room.go
The mapper generates a map of rooms in a zone, starting from the Root Room ID.
However, if the zone contains other rooms that are disconnect from the main group of rooms, or are reached via an unconventional exit (doesn't have a coordinate direction it exits to), they are being left out.
While still disconnected, this change allows those areas to have their own sub-maps that are accessed based on roomId now instead of a blanket zone name.
- mapper now has a separate cache that maps roomId's to their "zone cache"
- Simplified the pre-cache logic
- Renamed `GetZoneMapper()` => `GetMapper()`
=> Mapper fixes

_datafiles/world/default/mobs/frostfang/scripts/2-guard.js, _datafiles/world/default/mobs/frostfang/scripts/26-frostfang_citizen-locketsadness.js, internal/plugins/plugincallbacks.go, internal/plugins/plugins.go, internal/scripting/module_func.go, internal/scripting/scripting.go, modules/README.md, modules/follow/follow.go
Adds support for scripting functions defined in modules.
- module/plugin support for adding scripting functions `AddScriptingFunction(funcName string, funcVal any)`
- Created an example/first case use of this in guard script (checks for followers and tells them to get lost)
=> Module scripting functions

Makefile, main.go
A couple small changes around start up and running the mud.
- Removing a missed reference to `ungenerate` left in accidentally.
- No longer building binary with `make run`
- Adding a time when starting mud that logs how long start up took.
=> Removing makefile `ungenerate` reference, adding start up timer.

.gitignore, Makefile, _datafiles/world/default/rooms/catacombs/89.yaml, _datafiles/world/default/rooms/dark_forest/878.yaml, _datafiles/world/default/rooms/endless_trashheap/142.yaml, _datafiles/world/default/rooms/endless_trashheap/152.yaml, _datafiles/world/default/rooms/frost_lake/828.yaml, _datafiles/world/default/rooms/frostfang/21.yaml, _datafiles/world/default/rooms/frostfang/269.yaml, _datafiles/world/default/rooms/frostfang/433.yaml, _datafiles/world/default/rooms/frostfang/6.yaml, _datafiles/world/default/rooms/frostfang/784.yaml, _datafiles/world/default/rooms/frostfang_slums/436.yaml, _datafiles/world/default/rooms/frostfang_slums/462.yaml, _datafiles/world/default/rooms/frostfang_slums/474.yaml, internal/events/eventtypes.go, internal/hooks/RebuildMap_HandleMapRebuild.go, internal/hooks/hooks.go, internal/mapper/mapper.go, internal/mutators/mutators.go, internal/plugins/plugins.go, internal/rooms/roommanager.go, internal/rooms/rooms.go, internal/rooms/save_and_load.go, internal/usercommands/admin.build.go, internal/usercommands/admin.room.go, main.go
The goal of this PR is to split Room data files into two save forms:
1. The "Template", saved in `_datafiles/world/{worldname}/rooms/` which is just the normal, empty state room definition. This is how the room should be loaded into the memory the first time it is ever encountered. Items shouldn't be on the floor (unless it is desired to start with an item on the floor), gold, containers, etc. are all in their initial state.
2. The "Instance", saved in `_datafiles/world/{worldname}/rooms.instances/` which is everything (or most things) that have changed about the room and are worth saving in case the room gets unloaded from memory.
- Updated room "Template" data files to remove random objects that were saved and committed into rooms in the past.
- Instance loading/saving and Template …
=> Room instances

internal/rooms/ephemeral.go
Building for 32-bit is giving this error:
`cannot use roomIdMin64 (untyped int constant 1000000000000) as int value in assignment (overflows)`
Even though there is runtime detection for the integer bitsize, we still need to trick the compiler.
This sets it to the 32 bit value and then multiplies it by 1000 if the maxint is over this number.
- Changed the way we check for which minimum ephemeral RoomId value to use.
=> CI build related code changes

_datafiles/world/default/mobs/tutorial/scripts/58-training_dummy.js, _datafiles/world/default/rooms/tutorial/900.js, _datafiles/world/default/rooms/tutorial/901.js, _datafiles/world/default/rooms/tutorial/902.js, _datafiles/world/default/rooms/tutorial/903.js, internal/mobs/mobs.go
This ensures that delays for mob commands are based on the last executed command, not when every command was entered. This way stacking several commands with delays will actually delay in an expected manner.
- Tracking last turn time for mob commands, using to augment further commands.
- Updated tutorial scripts to reflect these changes.
https://github.com/GoMudEngine/GoMud/issues/377
=> Fix for mob delayed command stacking

internal/hooks/NewRound_AutoHeal.go, internal/rooms/roommanager.go
This puts every player into a copy of the `DeathRecoveryRoom` when they die, instead of players sharing a room.
- On death, players go to an ephemeral copy of the death recovery room.
- Fixed a small logic in auto-healing
=> `DeathRecoveryRoom` adjustments

internal/rooms/rooms.go, internal/rooms/rooms_test.go
Refactor the Room.FindNoun method to improve multi‑word noun matching, alias resolution, and plural/singular handling. This change ensures that full‑phrase lookups (e.g. “rocky island”) are tried first, aliases are unwrapped recursively, and common plural forms (…ies, …es, …s) are handled in a predictable order. It also fixes previously failing tests for “ponies” and “rocky”.
- Reordered matching logic to test the entire input string first, then each individual word, before falling back to plural/singular rules.
- Simplified alias handling by unwrapping any number of :‑prefixed aliases in a single loop.
- Consolidated pluralization/singularization checks.
- Removed the old nested split‑and‑append heuristic in favor of a clear candidate list built via util.SplitButRespectQuotes.
- Updated …
=> Updated FindNoun to fix issue 356

.github/RELEASING.md, .github/workflows/build-and-release.yml, .github/workflows/docker-package.yml, .github/workflows/run-tests.yml
This pull request updates the GoMud release workflows by modifying the GitHub Actions workflow files to utilize a new semantic versioning pattern and improved version injection into the built binaries and release artifacts.
- Modified docker-package workflow to use the semantic version tag pattern "v*.." and added a RELEASE_VERSION environment variable.
- Updated build-and-release workflow to trigger on release tags, add a code generation step, inject the release version into build commands via ldflags, and update artifact naming for releases.
- Modified `.github/workflows/docker-package.yml` and `.github/workflows/build-and-release.yml`
=> Update GoMud release workflows

internal/characters/alignment_test.go, internal/characters/character.go, internal/characters/character_test.go, internal/characters/charminfo_test.go, internal/characters/cooldowns.go, internal/characters/cooldowns_test.go, internal/characters/formattedname_test.go, internal/characters/kdstats_test.go, internal/characters/mobmastery_test.go, internal/characters/shop.go, internal/characters/shop_test.go, internal/characters/worn_test.go
Expanded the test coverage of the character package to 24.3%, focused on functions that were simple to generate tests on.
=> Added tests to character package

internal/badinputtracker/badinputtracker_test.go, internal/buffs/buffs_test.go, internal/buffs/buffspec.go, internal/buffs/buffspec_test.go
Added generated tests to `buffs` and `badinputtracker` packages.
- `github.com/GoMudEngine/GoMud/internal/buffs 0.306s  coverage: 25.8% of statements`
- `github.com/GoMudEngine/GoMud/internal/badinputtracker   0.351s  coverage: 100.0% of statements`
=> Added tests to buffs and badinputtracker packages

modules/gmcp/files/data-overlays/config.yaml, modules/gmcp/files/data-overlays/keywords.yaml, modules/gmcp/files/data-overlays/mudlet-config.yaml, modules/gmcp/files/datafiles/templates/help/checkclient.template, modules/gmcp/files/datafiles/templates/help/client.template, modules/gmcp/files/datafiles/templates/help/discord.template, modules/gmcp/files/datafiles/templates/help/mudletmap.template, modules/gmcp/files/datafiles/templates/help/mudletui.template, modules/gmcp/gmcp.Mudlet.go, modules/gmcp/gmcp.go
This adds the ability for the game to send Rich Presence information to Discord.
This will also add a better Discord integration directly in Mudlet:
By default it sends the following information:
```
DiscordApplicationID: "1298377884154724412",           // Default GoMud Discord Server
DiscordInviteURL:     "https://discord.gg/FaauSYej3n", // Default GoMud Discord Server
DiscordDetails:       "Using GoMudEngine",
DiscordState:         "Exploring the world",
DiscordLargeImageKey: "server-icon",                   // GoMud Discord Icon
DiscordSmallImageKey: "character-icon",                // Hover icon (not used)
```
As well as player name, level, area, party information and connection time.
The game name used in Discord comes from the application id or if not sent, the game name in …
=> Mudlet GMCP Discord Rich Presence functionality

internal/usercommands/admin.room.go
Currently when a user sets a room property, such as `room set title "Hello!"` they do not receive any response back letting them know the property was set.
- Sending the user text letting them know that the property was set on the room (following a similar format as exists for room exits).
=> Responding to user when they set a room property

.github/workflows/build-and-release.yml, .github/workflows/discord-notify.yml
This PR will update the build step to do a checkout action to fix an issue with the action run
- Added actions/checkout@v4 on build-and-release step
=> Added in checkout on the build step

internal/rooms/rooms.go
Fixed an issue where abbreviated direction commands (n, s, e, w, etc.) would fail with "command not recognized" when moving rapidly between rooms. The bug specifically occurred in rooms with ambiguous abbreviations (e.g., rooms with both "north" and "northeast" exits).
Changes:
- Add priority checking for standard direction abbreviations in FindExitByName
- Implement direct mapping for compass directions before fuzzy matching
- Support case-insensitive abbreviation matching
- Preserve fuzzy matching for custom exit names (portal, gate, etc.)
This ensures deterministic behavior where "n" always maps to "north" when that exit exists, eliminating problems in exit name resolution during rapid movement.
=> Minor fix for fuzzy exit name match

internal/characters/character.go, internal/races/races.go
Added validation to ensure TNLScale defaults to 1.0 when not specified or set to 0.
This can happen if a race for some reason is missing the tnlscale field or if it is set to 0 by mistake.
This prevents XPTL() from returning 0 experience required for next level, which was causing infinite leveling.
Changes:
- Added TNLScale validation in Race.Validate() to default to 1.0 if 0
- Added safety check in Character.RecalculateStats() as additional protection
=> Fixed infinite leveling bug when race TNLScale is 0 or missing

internal/mutators/mutators.go, internal/rooms/save_and_load.go
Removed early return statement that made the entire function body unreachable. This function is part of the SaveEqualityChecker interface used when saving room instances to determine if mutator lists differ from their templates.
This may be intential but prevents "make build" from successfully running "go vet".
I thought I'd address it just in case someone else runs into problems compiling using "make build".
If the early return false is intentional just reject this, but then we might want to remove the function altogether.
=> Fixed unreachable code in MutatorList.SkipInstanceSave

.github/workflows/auto-tag.yml, _datafiles/world/default/rooms/tutorial/901.js, _datafiles/world/empty/rooms/tutorial/901.js, internal/events/eventtypes.go, internal/hooks/RoomChange_SpawnGuide.go, internal/usercommands/appraise.go, internal/usercommands/skill.brawling.disarm.go, internal/usercommands/skill.brawling.recover.go, internal/usercommands/skill.brawling.tackle.go, internal/usercommands/skill.brawling.throw.go, internal/usercommands/skill.cast.go, internal/usercommands/skill.enchant.go, internal/usercommands/skill.inspect.go, internal/usercommands/skill.map.go, internal/usercommands/skill.peep.go, internal/usercommands/skill.portal.go, internal/usercommands/skill.protection.aid.go, internal/usercommands/skill.protection.pray.go, internal/usercommands/skill.protection.rank.go, internal/usercommands/skill.scribe.go, internal/usercommands/skill.search.go, internal/usercommands/skill.skulduggery.backstab.go, internal/usercommands/skill.skulduggery.bump.go, internal/usercommands/skill.skulduggery.pickpocket.go, internal/usercommands/skill.skulduggery.sneak.go, internal/usercommands/skill.tame.go, internal/usercommands/skill.track.go
Adds an event that fires when skills are used. Skill is not cancellable via event, simply allows for extra handling of skill usage.
- Added `SkillUsed` event type
- Removed auto-tag github workflow
- Fixing issue where player wasn't given sharp stick in tutorial
- Fixing issue where guide does not spawn for new players
=> Adding a skill use event, disabling auto-tag workflow

_datafiles/html/public/webclient.html, internal/util/util.go, internal/util/util_test.go
PR to capture fixing small bugs reported/discovered.
* Fixing a bug where splitting room descriptions that already have line breaks causes duplication of line data.
* Webclient crops left side of text when in iframe (not present in /webclient-pure). This should fix it.
* https://github.com/GoMudEngine/GoMud/issues/418
* https://github.com/GoMudEngine/GoMud/issues/422
=> Miscellaneous small bugs reported
