GoMudEngine/GoMud

_datafiles/templates/character/inventory.template
usercommands/usercommands.go

* Fixed a line to include an extra character
* Added a default `score` alias

Added a score alias and fixed a line width issue

---

Makefile
README.md
notes.md

* Mostly documentation improvements for clarify for new users.

Docs, notes, makefile improvements

---

README.md

* Added a thumbnail and link to a youtube help playlist
* Added a docker-compose string to start the server from docker.

Adding link to videos and docker-compose string

---

_datafiles/config.yaml
_datafiles/keywords.yaml
configs/configs.go
connection/connectiondetails.go
inputhandlers/cleanser.go
keywords/keywords.go
main.go
mobcommands/mobcommands.go
mobcommands/throw.go
term/term.go
usercommands/alias.go
usercommands/ask.go
usercommands/help.go
usercommands/look.go
usercommands/skill.brawling.throw.go
usercommands/usercommands.go
usercommands/whisper.go
users/userrecord.go
world.go

* Moved aliases and keywords mostly to a yaml file
* Added some auto-complete functionality when tab is pressed

Autocomplete and keywords file

---

rooms/rooms.go
util/util.go
world.go

* Added some function receivers for locks to test whether a lock is lockable
* Added a utility function to break a string into a series of parts for better keyword testing
* Cleaned up suggestion function, added context awareness for different commands

Added better context awareness for second word suggestions

---

Makefile
README.md
_datafiles/rooms/frostfang/784.yaml
notes.md
rooms/rooms.go
usercommands/README.md
usercommands/get.go
world.go

* Fixed container gold spawning
* Fixed autocomplete for gold in room and in containers
* Added/Changed various documentation

Some minor autocomplete changes and documentation

---

README.md
_datafiles/config.yaml
_datafiles/rooms/frostfang/25.yaml
_datafiles/rooms/frostfang/30.yaml
combat/combat.go
keywords/keywords.go
main.go
world.go

* Fixed an issue with unarmed combat showing "***Disabled***" instead of the racial "default" weapon name.
* Added some links to feature demo videos
* Fixed some prompt bugginess on redraw
* Auto-complete/suggestion only provides full name/sentence options when no text has been entered yet.

misc fixes to autocomplete, added some documentation(videos)

---

_datafiles/templates/help/set-prompt.template
characters/character.go
usercommands/set.go
users/userrecord.go
world.go

* Reworked some prompt token names
* Added more tokens
* Added `fprompt` which is used while player is aggro

Added fprompt, more tokens

---

_datafiles/ansi-aliases.yaml
_datafiles/config.yaml
_datafiles/keywords.yaml
_datafiles/templates/descriptions/inspect.template
_datafiles/templates/generic/sunrise.template
_datafiles/templates/generic/sunset.template
_datafiles/templates/help/set-prompt.template
buffs/buffspec.go
configs/configs.go
scripting/buff.go
scripting/room.go
templates/templatesfunctions.go
usercommands/time.go
usercommands/usercommands.go
users/userrecord.go
world.roundtick.go

* Added time of day and related configs
* Added prompt tokens for time of day or day/night icons
* Sunrise/sunset notifications

Cleanup timeofday

---

_datafiles/ansi-aliases.yaml
_datafiles/templates/help/set-prompt.template
configs/configs.go
connection/connection.go
connection/connectiondetails.go
gametime/gametime.go
gametime/gametime_test.go
main.go
scripting/docs/FUNCTIONS_UTIL.md
scripting/util_func.go
usercommands/admin.server.go
usercommands/time.go
usercommands/usercommands.go
users/userrecord.go
util/util.go
world.roundtick.go

* Added a `gametime` package and caching
* Added a bit more color to time
* Exported time util functions to scripting.

Standardized gametime and exported to scripts

---

_datafiles/items/other-0/4.js
characters/character.go
mobs/mobs.go
scripting/actor_func.go
scripting/docs/FUNCTIONS_ACTORS.md
scripting/docs/SCRIPTING_ITEMS.md
scripting/item.go
usercommands/drop.go
usercommands/eat.go
usercommands/get.go
usercommands/give.go
usercommands/sell.go
usercommands/stash.go
usercommands/storage.go
usercommands/trash.go
usercommands/use.go

This adds events for when items are picked up or dropped

Adding special item events for onLost/onFound

---

_datafiles/buffs/15.js
_datafiles/templates/help/adjectives.template
_datafiles/templates/help/set.template
buffs/buffs.go
characters/character.go
characters/formattedname.go

Fix a buff related bug, minor other changes

---

_datafiles/buffs/1.yaml
_datafiles/buffs/19.js
_datafiles/buffs/19.yaml
_datafiles/buffs/3.yaml
_datafiles/buffs/31.js
_datafiles/buffs/31.yaml
_datafiles/items/consumables-30000/30006.yaml
_datafiles/races/troll.yaml
_datafiles/rooms/frostfang/35.js
_datafiles/templates/descriptions/exits.template
_datafiles/templates/help/emote.template
_datafiles/users/admin.yaml
buffs/buffspec.go
copy-rpi.sh
mobs/mobs.go
rooms/biomes.go
rooms/roommanager.go
usercommands/emote.go
usercommands/go.go
usercommands/train.go
users/userrecord.go

* Biomes can apply buffs when entering rooms
* Minor API changes
* Changed the western gate to allow player through.

Addition of biome specific buffs, misc content adjustments

---

_datafiles/buffs/1.yaml
_datafiles/buffs/31.js
_datafiles/keywords.yaml
_datafiles/rooms/frostfang/35.js
_datafiles/templates/help/killstats.template
_datafiles/users/admin.yaml
buffs/buffs.go
characters/kdstats.go
mobcommands/suicide.go
usercommands/killstats.go
world.go

* Fixed some logic issues
* Removed a buff flag that was used for debugging
* Adjusted some content/messaging
* Improved `killstats`
* Fixed Permabuff yaml name

Fixing some broken logic

---

_datafiles/rooms/tutorial/900.js
_datafiles/rooms/tutorial/901.js
_datafiles/rooms/tutorial/902.js
_datafiles/rooms/tutorial/903.js
_datafiles/rooms/tutorial/990.js
_datafiles/rooms/tutorial/991.js
_datafiles/rooms/tutorial/992.js
_datafiles/rooms/tutorial/993.js
_datafiles/users/admin.yaml
characters/formattedname.go
colorpatterns/colorpatterns.go
main.go
mobcommands/portal.go
scripting/docs/FUNCTIONS_UTIL.md
scripting/room_func.go
scripting/util_func.go
templates/prebakes.go
templates/templates.go
usercommands/skill.portal.go
world.roundtick.go

* More support for specifying color pattern tag with `:` prefix (portal custom title)
* Overall improvements and flexibility to color patterns
* A lot more color patterns and debug start up display of patterns

color patterns improvement

---

copy-rpi.sh
webclient/webclient.html

websocket connects to host of web page.

Websocket change

---

characters/character.go
copy-rpi.sh
inputhandlers/login.go
users/users.go

misc fixes

---

main.go
webclient/webclient.html

Fixing up some faulty rendering/code

modifying webclient/websocket code

---

_datafiles/users/admin.yaml
inputhandlers/login.go
webclient/webclient.html

masking password entry in web client

---

combat/combat.go
copy-rpi.sh
inputhandlers/login.go

* Fixed a bug where you could get stuck in infinite combat without attacking
* Fixed a bug where webclient gets stuck in masked text on new account creation

Fixing combat bug and webclient getting stuck with masked text

---

_datafiles/rooms/frostfang/879.yaml
world.roundtick.go

* Caching and comparing the last command prompt and avoiding resending if nothing has changed.

Fixing a spammy command prompt

---

_datafiles/templates/descriptions/room-title.template
_datafiles/templates/descriptions/room.template
_datafiles/templates/generic/sunrise.template
_datafiles/templates/generic/sunset.template
_datafiles/templates/help/map.template
inputhandlers/systemcommands.go
rooms/biomes.go
rooms/effects.go
rooms/roommanager.go
rooms/rooms.go
templates/templatesfunctions.go
usercommands/skill.peep.go
webclient/webclient.html
world.go
world.roundtick.go

* Fixed an error with `peep` rendering inventory
* Added room effects, starting with wildfire which spreads from room to room... if in a flammable biome (forest)
* Fixed rendering of sunset
* Some updates to webclient, changing from RGB styles to classnames, predefining classnames on load.

Room Effects

---

_datafiles/ansi-aliases.yaml
_datafiles/mobs/frostfang/scripts/38.js
_datafiles/rooms/frostfang/5.yaml
_datafiles/users/admin.yaml
configs/configs.go
mobcommands/say.go
mobcommands/sayto.go
scripting/actor_func.go
scripting/docs/FUNCTIONS_ACTORS.md
scripting/docs/FUNCTIONS_UTIL.md
scripting/util_func.go
usercommands/README.md
usercommands/say.go

* Several additional scripting functions/methods
* Player guide gives tips to help get started now.
* Updated some bad readme info
* Updated color of "say" text, and made a color class for it.

Guide tips

---

_datafiles/buffs/36.yaml
buffs/buffspec.go
characters/character.go
inputhandlers/login.go
mobcommands/break.go
mobcommands/broadcast.go
mobcommands/drop.go
mobcommands/equip.go
mobcommands/gearup.go
mobcommands/get.go
mobcommands/give.go
mobcommands/look.go
mobcommands/mobcommands.go
mobcommands/remove.go
mobcommands/suicide.go
usercommands/character.go
usercommands/skill.brawling.disarm.go
users/users.go

This is experimentation of a fun idea that would allow you to hire a copy of an alt character to join you. It will likely need more changes, or even possibly to be removed if it ends up too exploitative.
* `character` alt rooms now have a `hire` option. The cost to hire is `(250 * Level) + ValueOfGear`.
* Hired alts have their backpack gear removed.
* Hired alts get a condition applied that prevents them from removing or dropping any gear.

Hire Alt Characters

---

_datafiles/mobs/frostfang/38.yaml
_datafiles/mobs/frostfang/scripts/38.js
_datafiles/rooms/frostfang/6.yaml
_datafiles/templates/admincommands/help/command.skillset.template
_datafiles/templates/help/guide.template
_datafiles/users/admin.yaml
events/eventtypes.go
mobcommands/go.go
mobcommands/suicide.go
rooms/roommanager.go
skills/skills.go
term/gmcp.go
term/mdsp.go
term/mdsp_test.go
usercommands/admin.skillset.go
usercommands/admin.zap.go
world.go

* Guide now won't come back for 5 minutes if killed
* Guide can be told to shaddup
* Guide helpfile
* Guide should be _slightly_ less annoying in general
* Admin user starts with full skills for testing purposes
* Started fleshing out GMCP and MDSP protocol handling
* `zap` admin command can target player/mob without being in combat
* `skillset` command can now set skill for `all` to a level
* admin default account starts fully skilled up

Player Guide Mob, GMCP, MDSP, admin commands

---

connection/clientsettings.go
connection/connection_pool.go
connection/connectiondetails.go
events/eventtypes.go
inputhandlers/term_ansi.go
inputhandlers/term_iac.go
main.go
rooms/roommanager.go
term/gmcp.go
term/telnet.go
usercommands/default.go
usercommands/skill.map.go
usercommands/usercommands.go
users/userrecord.go
webclient/webclient.html
world.go
world.roundtick.go

* Moved client settings to the network layer
* Added some basic support for GMCP, mainly around room info and players leaving/entering.
* Tracking GMCP modules reported by client.
* Added `default` command, which attempts to perform a default action for a room (usually just look)

GMCP updates

---

connection/clientsettings.go
connection/connection_pool.go
inputhandlers/term_iac.go
rooms/roommanager.go
world.go
world.roundtick.go

* Detecting/Flagging Mudlet client connections
* Eliminating unnecessary json Marshalling for basic GMCP json
* Sending offline notification for users when they win an auction and aren't online

Misc changes

---

_datafiles/config.yaml
buffs/buffs.go
buffs/buffspec.go
characters/character.go
combat/combat.go
configs/configs.go
items/items.go
items/itemspec.go
pets/pets.go
statmods/statmods.go
usercommands/online.go
users/onlineinfo.go
users/userrecord.go
webclient/stats.go
webclient/webclient.go
world.go
world.roundtick.go

Mods and Admins may need to lurk in game for various reasons. This change allows them to remain in game past max idle time (via configuration).
* `TimeoutMods` in `config.yaml` - `boolean` value.
* Fixing a bug with zombie flag
* Statmods moved to own package
* Updated homepage stats/info readout.

Mod/Admin Timeout config

---

README.md
_datafiles/keywords.yaml
_datafiles/templates/admincommands/help/command.modify.template
_datafiles/templates/help/password.template
usercommands/admin.modify.go
usercommands/admin.mudmail.go
usercommands/password.go
usercommands/usercommands.go
users/userrecord.go

* Users need a way to change their passwords.
* Admins need a way to promote/demote mods or other admins
* Small update to readme
* Added terms to help list
* Added `modify` admin command (only can change permissions right now)
* Added `password` user command to change password.
* Renamed `massmail` to `mudmail`

Password and Admin Modify command

---

rooms/gamelock.go
statmods/statmods.go
term/gmcp.go
usercommands/picklock.go

* Locks can have traps, which are just buffId's that get applied on failure.
* StatMod of Picklock presolves locks somewhat

lock presolve (from StatMods), lock traps.

---

characters/character.go
gametime/gametime.go
items/itemspec.go
mobcommands/portal.go
usercommands/admin.spawn.go
usercommands/inventory.go
usercommands/skill.enchant.go
util/util.go
web/admin.go
web/admin.items.go
web/html/admin/index.html
web/html/admin/itemdata.html
web/html/admin/items.html
web/html/public/webclient.html
web/web.go
world.go

* Fixed a bug related to time strings
* Eliminated "holdable" item subtype - now just offhand.
* Removed several item subtypes that weren't in use.
* Added a basic item viewing admin tool.

Item Admin Basics

---

_datafiles/html/admin/_footer.html
_datafiles/html/admin/_header.html
_datafiles/html/admin/mobs/index.html
_datafiles/html/admin/mobs/mob.data.html
_datafiles/html/admin/races/race.data.html
_datafiles/mobs/frostfang/7-wench.yaml
feature-screenshots/README.md
mobs/mobs.go
web/admin.items.go
web/admin.mobs.go
web/admin.races.go
web/template_func.go
web/web.go

* Mob view admin tool
* Time string tip
* Misc small adjustments

Adjustments to admin tool

---

_datafiles/config.yaml
_datafiles/keywords.yaml
_datafiles/templates/help/leaderboard.template
_datafiles/users/admin.yaml
internal/characters/alts.go
internal/configs/configs.go
internal/leaderboard/leaderboard.go
internal/usercommands/leaderboard.go
internal/usercommands/usercommands.go
main.go
world.go

* Added `leaderboard` command and helpfile
* Added config value for max leaderboard entries per leaderboard

leaderboard command

---

_datafiles/config.yaml
_datafiles/mutators/death_recovery.yaml
_datafiles/rooms/shadow_realm/75.yaml
internal/configs/configs.go
internal/usercommands/character.go
internal/usercommands/history.go
internal/usercommands/start.go
internal/users/userrecord.go
internal/users/users.go
main.go
world.go
world.roundtick.go

* Added a short time display config option
* Modified player logs to use shorter category and date
* Shadow realm now uses a mutator instead of hard coded recovery

Logs and death

---

_datafiles/html/admin/_header.html
_datafiles/html/admin/mutators/index.html
_datafiles/html/admin/mutators/mutator.data.html
internal/configs/configs.go
internal/flags/flags.go
internal/gametime/zodiac.go
internal/mutators/mutators.go
internal/rooms/roomdetails.go
internal/rooms/roommanager.go
internal/rooms/rooms.go
internal/rooms/zoneconfig.go
internal/usercommands/shout.go
internal/web/admin.mutators.go
internal/web/web.go
main.go

* Added -port-search flag (also -h flag)
* Started mutator admin
* Seeded random numbers for shuffling zodiac

port-search

---

_datafiles/html/admin/_footer.html
_datafiles/html/admin/_header.html
_datafiles/html/admin/mobs/mob.data.html
_datafiles/html/admin/mutators/mutator.data.html
_datafiles/html/admin/rooms/index.html
_datafiles/html/admin/rooms/room.data.html
_datafiles/templates/help/damage.template
internal/rooms/biomes.go
internal/web/admin.rooms.go
internal/web/template_func.go
internal/web/web.go

* Added more details on mutator data
* Room View

Web Admin Additions

---

_datafiles/templates/admincommands/help/command.item.template
_datafiles/templates/admincommands/help/command.mob.template
_datafiles/templates/admincommands/help/command.spawn.template
_datafiles/templates/character/start.racelist.template
_datafiles/templates/tables/numbered-list.template
internal/characters/character.go
internal/items/itemspec.go
internal/items/newitemfile.go
internal/mobs/mobs.go
internal/mobs/newmobfile.go
internal/templates/name_description.go
internal/usercommands/admin.item.go
internal/usercommands/admin.mob.go
internal/usercommands/admin.spawn.go
internal/usercommands/start.go
internal/usercommands/usercommands.go

* `item create` and `item spawn` are now commands (no longer `spawn item`)
* Help files
* Creates items via a series of prompts
* Removed `characters/start.racelist.template` and now use `tables/numbered-list` as a numbered list.

Item create command

---

README.md

The path `localhost/client` is incorrect and should be `localhost/webclient` (due to changes from #160 )
Super cool project btw! I hope to dig in more over the next few days

Update web client path in README.md

---

_datafiles/config.yaml
internal/configs/config_types.go
internal/configs/configs.go
internal/configs/configs_test.go
internal/events/listeners.go
internal/gametime/zodiac.go
internal/hooks/PlayerDespawn_HandleLeave.go
internal/hooks/hooks.go
main.go

* Secret config type -
* By default `String()` method returns redacted
* Configs can specify `env` tag to indicate an overriding environment variable (if present)
* Events can be registered to force last
* Fix to colorize goodbye message

ENV Config values

---

internal/integrations/discord/client.go
internal/integrations/discord/listeners.go
internal/util/util.go
main.go
world.go

* Added util.ANSIStrip()
* Error messages log to discord if able
* Cleaned up noisy error logs, downgraded to warn

Discord error logging

---

_datafiles/html/public/webclient.html
provisioning/copy-rpi.sh

* Setting websocket port from config
* provisioning script change

Webclient fix

---

_datafiles/html/public/webclient.html

* Remove port specification
* Port is included in `location.host` if not port 80

Fixing host

---

internal/combat/combat.go
internal/connections/connectiondetails.go
internal/connections/connections.go
internal/connections/heartbeat.go
internal/integrations/discord/client.go
internal/integrations/discord/listeners.go
world.go

* many `Error` logs turned to `Warn`
* Suppressed some messages
* adjusted some messages.

Cleaning up spammy errors

---

internal/connections/connections.go
internal/integrations/discord/client.go
internal/integrations/discord/listeners.go

* Moved requests to goroutines
* Added a 30 second backoff if requests fail

Discord efficiency

---

internal/events/eventtypes.go
internal/hooks/DayNightCycle_NotifySunriseSunset.go
internal/hooks/NewRound_DoCombat.go
internal/hooks/NewRound_MobRoundTick.go
internal/hooks/NewRound_SpawnLootGoblin.go
internal/hooks/NewRound_SunriseSunset.go
internal/hooks/hooks.go
internal/integrations/discord/client.go
internal/integrations/discord/listeners.go
internal/templates/templatesfunctions.go
main.go
world.go

* Added `DayNightCycle` as event type
* Handling in discord integration
* Miscellaneous cleanup/typo fixes
Discord integration:

DayNightCycle events

---

.github/workflows/build-and-release.yml

* Changing property from `embed-footer-text` to `embed-url`
* Removing markdown from url

Discord webhook url property change

---

internal/integrations/discord/client.go
internal/integrations/discord/listeners.go

* Removing the following notification:
* `☀️ Day ### begins.`

Removing Discord "New day" notification

---

_datafiles/world/default/templates/character/levelup.template
_datafiles/world/empty/templates/character/levelup.template
internal/events/eventtypes.go
internal/hooks/LevelUp_SendLevelNotifications.go
internal/integrations/discord/client.go
internal/integrations/discord/listeners.go
internal/integrations/discord/types.go
internal/users/userrecord.go
internal/web/README.md
internal/web/web.go

This is a number of small fixes, adjustments, or documentation changes.
* Added basic README.md for web
* All files that begin with `_` in the web root or requested folder are automatically included in all html page loads.
* Discord messages now use the embed feature to make them stand out a little more.
* Gaining multiple levels at once is now accounted for.

Fixes and Adjustments

---

_datafiles/world/default/ansi-aliases.yaml
_datafiles/world/default/keywords.yaml
_datafiles/world/default/templates/admincommands/help/command.skillset.template
_datafiles/world/default/templates/character/levelup.template
_datafiles/world/default/templates/help/stat-train.template
_datafiles/world/empty/ansi-aliases.yaml
_datafiles/world/empty/keywords.yaml
_datafiles/world/empty/templates/admincommands/help/command.skillset.template
_datafiles/world/empty/templates/character/levelup.template
_datafiles/world/empty/templates/help/stat-train.template
internal/auctions/auctions.go
internal/events/eventtypes.go
internal/hooks/Looking_HandleLookHints.go
internal/hooks/NewRound_AuctionUpdate.go
internal/hooks/hooks.go
internal/integrations/discord/client.go
internal/integrations/discord/listeners.go
internal/mobcommands/suicide.go
internal/mobs/mobs.go
internal/scripting/mob.go
internal/usercommands/admin.skillset.go
internal/usercommands/auction.go
internal/usercommands/help.go
internal/usercommands/list.go
internal/usercommands/look.go
internal/users/userrecord.go
world.go

Miscellaneous small changes/improvements. Some are part of migrating the system over to events piece by piece.
* Added events for auctions.
* Added discord event handlers for auctions
* Fixed a bug with new interactive prompts not immediately displaying to the user
* Adding help for `stat train` etc.
* Added hint to train stats when leveling up.
* Added optional target for `skillset` admin command.
* Reduced logging, specially for onIdle script event check on mobs.
* Added `Looking` event
* Added `user.DidTip()` to check/track tips
* First tip added is at shops, hinting to use `list` to view what's for sale.

Misc small fixes

---

internal/leaderboard/leaderboard.go

This fixes a small logic bug introduced in the last PR where all of a users characters wouldn't be considered for all leaderboards.

Leaderboard logic fix

---

internal/leaderboard/leaderboard.go
internal/templates/templatesfunctions.go
internal/usercommands/character.go
internal/usercommands/leaderboard.go
internal/util/util.go

Fixes a few minor issues with leaderboards, modifies number formatting and centralizes it in the util package.
Leaderboards:

Leaderboard quickfix

---

internal/usercommands/go.go
internal/usercommands/usercommands.go

Adding the gmcp.Room.Wrongdir message to failed movement.
I don't know if I have found them all, but if I find more, I'll push another PR to the repo.
/Morquin

Adding gmcp.Room.WrongDir

---

_datafiles/world/default/ansi-aliases.yaml
_datafiles/world/empty/ansi-aliases.yaml
internal/events/eventtypes.go
internal/hooks/Broadcast_SendToAll.go
internal/hooks/CharacterCreated_BroadcastNewChar.go
internal/hooks/hooks.go
internal/rooms/roommanager.go
internal/rooms/rooms.go
internal/usercommands/character.go
internal/usercommands/start.go
internal/users/userrecord.go
modules/leaderboards.go

* Centralized some alt char code into the user record
* Added events/handlers/colors for `CharacterChanged` and `CharacterCreated`
* Removed a debugging print statement

Alt Char adjustments

---

internal/users/index.go
internal/users/users.go

* Altered the way highest userId is tracked in user index.

Fix for highest userId inaccuracy

---

internal/users/userrecord.go
internal/util/util.go
internal/util/util_test.go

* Modified the way md5 hashes are generated and modulus taken.

Correcting some use of md5 lib

---

Makefile
internal/mapper/mapper.go
internal/mobcommands/cast.go
internal/plugins/plugins.go
internal/usercommands/skill.cast.go
internal/web/web.go
modules/README.md
provisioning/Dockerfile

* Updated docker image version
* Changed docker compose yaml file for make target
* `mapper. PreCacheMaps()` now sorts before precaching zones to keep coordinate system more consistent.
* Added experimental function exporting in plugins.
* Goal is to allows for optional cross module dependencies

Miscellaneous small changes

---

internal/web/web.go

* Changing logic order to require https server if redirect is enabled.

Https adjustments

---

_datafiles/config.yaml

* `LootGoblin. MinimumItems`: `2`=>`3`
* `LootGoblin.IncludeRecentRooms`: `false`=>`true`
* `Timing. RoundsPerAutoSave`: `450 (30 minutes)`=>`225 (15 minutes)`
* `Network. MaxTelnetConnections`: `50`=>`100`
* `Network. HttpsPort`: `443`=>`0`
* `Network.ZombieSeconds`: `30` => `60`

Config.yaml default adjustments

---

modules/all-modules.go

- Adds missing `follow` include

Adding follow module incldue

---

modules/webhelp/files/datafiles/html/public/help-details.html

Quick PR to remove some test style code that was left in.

Removing test style/include font

---

_datafiles/world/empty/templates/admincommands/help/command.deafen.template

Addressing a few typos in the deafen command.
- Changed `cusotm` to `custom`
- Changed `communcations` to `communications`

Addressing a few typos in the deafen command
